name: softbase
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #firebase
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.1
  firebase_remote_config: ^4.0.1
  firebase_analytics: ^10.4.3

  #dependency injection
  get_it: ^7.6.0
  injectable: ^2.1.2

  #state Management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  copy_with_extension: ^5.0.3

  #image
  lottie: ^2.2.0
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3

  #language
  easy_localization: ^3.0.1

  #local storage
  hive: ^2.2.3

  #file
  image_picker: ^0.8.7+1
  path_provider: ^2.0.11

  #network
  http: ^0.13.4
  retrofit: ^4.0.1
  dio: ^5.2.1+1
  floor: ^1.4.1
  awesome_dio_interceptor: ^1.0.0

  #other
  oktoast: ^3.3.1
  lint: ^2.1.1
  page_transition: ^2.0.9
  meta: ^1.9.1
  barcode_widget: ^2.0.4
  pinput: ^2.2.0
  audio_video_progress_bar: ^1.0.1

  libs_text_field:
    path: ../libs_text_field
    # git:
    #   url: git@bitbucket.org:maple-labs/connectsdk-provider-flutter.git
    #   ref: firetv_1.0.1

  libs_message:
    path: libs_message
    # git:
    #   url: git@bitbucket.org:maple-labs/connectsdk-provider-flutter.git
    #   ref: firetv_1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  retrofit_generator: ^7.0.6
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.6
  copy_with_extension_gen: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/jsons/

  fonts:
    - family: InterThin
      fonts:
        - asset: assets/fonts/Inter_thin.ttf
          style: italic

    - family: Inter_Medium
      fonts:
        - asset: assets/fonts/Inter_Medium.ttf

    - family: Inter_Bold
      fonts:
        - asset: assets/fonts/Inter_Bold.ttf

    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf

    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

